name: Test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    name: Test action-gh-release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
    env:
      ACTIONS_RUNNER_DEBUG: "true"
      ACTIONS_STEP_DEBUG: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Make some big artifacts for release
        run: ./make-artifacts.sh
      - name: Make the release
        #uses: softprops/action-gh-release@v2
        uses: xen0n/action-gh-release@7a84fdd372e1b038f8233f174968919d7742a686
        with:
          files: ./test*
          #preserve_order: true  # test
